env:
  global:
    - PROJECT_NAME=IGP
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: "QUOe88n4VsGL6dwXTTc2DPGlKGcnLWMRR9jLf1xpLqFpvohHA8G6WuImjLwZmESVtByGD98JuQRcVtms7Wcc9pRsgLb8r7G/h0MlsrpVPvoUSO8oxzS+H0kN/gQWwQNKKDFlcOVHIcascCilsPZN6BkF5+zgyEVgTmoSyPbkNIOb55MWgeuMUXoCFCta8aAlZa5oHZGVRhLazNCiaWQVys6twGt9FfVk3eS3JEOb5Orf/shan5I7cy04lGWtHf8+zHF0RKe91gLRVylqs6WbiJk/Hi1fOZgpbl0fcbVFFg7Uaw32HDjoCQUAShnrSzfOt5R9yVdDWtNYViaoZrqAh0ZWLr7Jy7lIMVEZBdRNOdj4N1x7ugH1fW/Q4Sr0lBw0R8XOPZCuEQrJqXQUbkCaXUxS5B/GU0ossF0qICNvNWzqOOUGrMVnjAT/DZq8kRMaP8wqFgFccuJhNA+9xvspk6IHmeP9UUWk5OozH2Dq9DNrSbkYzEbAzBaOCDORVfJa98ezhfyx8kWzarDvCPTTJ66M1aPlcMnydvFJzqhkLuzJ1lYbjzBGhD4cAsbg+uQJVGvKTIuS6zCLgU6raxeFbOx04jcgoiVApT2wxb0y7VYfJmU8NTbX2ud+IBvCSxTIYtjU3IDNS+3S0JazZ7FBEo8b6Ont+N5gkm3LuGLR3uw="
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    - secure: "YnBGJ44QQHO3x8mEThEzxyhqljpXZAudbgtl0nODT59B3IPri3I1BjmYK2PEiB+jb3F06BaVk0kZR5saQ5WyKSUyAvDcbRFZMwsBb+7qHLNOSL49iSikILTAHVUBNDpqxpT5CzVzg7EhuT7i6pUJvEWTbMkB3XXvhKyy01Xr8NS1ReV+VvqtU+Z+tcZ4A4kQ8qkKhKL5CoLkaSH6II5OR9zA31QXVimH10AEI/p48h0pGcvMv9a6v5W5qyGYTPyqN79RW2lOlKdqN2q7T15Zg3z5/8ngTAB9E6qmUOhquBGD0wizRLCNx2BzuKCtNWMyEghWaFdJ6dcstiuV5nfAGZCw28AEb7ec5d77UEGoCoN5OHfIU9JB5ffzHCvOAHH+W85V5WbqkcgNe+Xenva3nviOElw7yTgM2u0BJDVEn3y96aOhpuxrcMLO5GTtcFhpy664t/mUIxnvEzF20rkp//qV/8cEFk4mJYBaRijesQALUgTjwu6usi2TbTUfi7675mrdm9wyCEd4TIo9inVrXmQfQML8UAAQlEU8FpQhgDll1cxRXCJNnDMHrQtyXiZwKX9u0h0JsCMynRy3aXQ7N3p7WH2L0al9G7J4xPPgaDee5PzUGa/sOi3liKuK92IJibMeQNG5IY9qMOTqg3cvnpyHIbahMocUT24FHimKcxs="
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta