env:
  global:
    - PROJECT_NAME: "processwire-demo"
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: "h9rsNRaA4/0klbEVyUBL2yy1+tg26iejdcAIhhZNMGaxA3mnOpR390srloeUORhIwRk48yPBEsmwHEOwDkC2/nn5HjBn18d5BWBbmMjQbYdpyupwha4isnqmBqy3wRYQ7AFf4AJldvACbm2NpW4PKZ/FZa0kU+/Gz3IFv4uGBEZ1s+h10Mne099izSHqTyusSiRv1HjLN+Vhz2pDiBPL6NJF0ZhE2K7uZyrDhLLn38tx9p3Wj/fovWn+xAKORtM8+97EDSwu8nGZnim6W8M85Y6PJ+KWrrsTRBQgn+WQ9Z8ctrDOiw7bj5biQx3MDlhAEyOe/yH0QMnDDNk+8PjnwXynQ5x3lTfaDP+iUGHLrvc8xXbEiudu5RP10yq4kMm+8IATxGMC8L3XrYb5aqD1kx72aw7IPEkVq7ZEPCX6/pok4FgLgxJInbwvFR3u5IWvRUvFcQxvsme1GQbyO/4RSOnnrfMY36q/JilJ0200A9dths2PtaXwFVSlERPvOQMRkT4WRJqYQbLrGqgd7BuSyN+9lqj60wIabeN68+949b0MK/l6PdpLxtoGH2a+qHJBqWcKpvi+IYDWbt3iQYXTqaIDXh4FzwylZ3ZSDQH8/RuGzQiSWN07ylVv5RSCdYFuy4HiSzc2xI+AC67Dt1cbqXo/nGzfvuYfvulh6wFwGhI="
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    # secure: ""
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: /tmp/git-ftp push -s $TRAVIS_BRANCH -v
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: /tmp/git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta